#################
# Ubuntu Image for BOINC-MIDAS usage
#
# Specifically designed to run BOINC jobs from a set of input files
# Contains bash, curl, wget, tar, python3, pip3 as default
#################


FROM ubuntu:16.04

COPY Mov_Specific.py /work/Mov_Specific.py


RUN mkdir -p /root/shared/resultsr &&\
    apt-get update && apt-get install curl wget tar python3 python3-pip -y
