##########################
# BOWTIE BOINC TEST
#
# Designed to test if curl is a problem
##########################

FROM carlosred/bowtie:latest

COPY s_cerevisiae.ebwt.zip /data/s_cerevisiae.ebwt.zip


# Test commands

RUN cd /data && unzip s_cerevisiae.ebwt.zip &&\
    bowtie -c s_cerevisiae ATTGTAGTTCGAGTAAGTAATGTGGGTTTG > res_bowtie.txt &&\
    python /Mov_Res.py
