<?php
//Added by Gerald Joshua
//Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$result = "";
$url ="";
if($_POST["tagExists"]){
	$url = "https://index.docker.io/v1/repositories/".$_POST["dockerName"]."/tags/".$_POST["tag"];
} else {
	$url = "https://index.docker.io/v1/repositories/".$_POST["dockerName"]."/images";
}
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($ch);
if (strpos($result, "not found") !== false)
	echo false;
else
	echo true;
curl_close($ch);
?>