<?php
// This file is part of BOINC.
// http://boinc.berkeley.edu
// Copyright (C) 2008 University of California
//
// BOINC is free software; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// BOINC is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

//Edited by Thomas Johnson III

// Also edited by Carlos Redondo

require_once("../inc/util.inc");
require_once('../inc/account.inc');
require_once("../inc/researchers_inout.inc");

//Added by Gerald Joshua
if(!isset($_SESSION))
  session_start();

if(isset($_SESSION['user'])){//Don't allow users who already logged in as a researcher to log in as a researcher again
  page_head(null, null, null, null,  null, "Already Logged In");
  echo "<center><h1>".tra("Already logged in as a researcher with username '").$_SESSION['user']."'</h1></center>";
} else {
  //Don't allow users who already log in as a volunteer log in as a researcher
  $user = get_logged_in_user(false);
  if ($user) {
      page_head("Already logged in as a volunteer");
      row2("You are logged in as $user->name",
          ".  <a href=\"logout.php?".url_tokens($user->authenticator)."\">Log out</a>"
      );
      page_tail();
      exit;
  } else {
    //End of the edit by Joshua
    page_head(null, null, null, null,  null, "Log In");
    echo "<br>";
    echo "<a data-toggle=\"tooltip\"  style=\"margin-left: 36%;font-size: 24px;border-bottom:1px dotted #000;text-decoration: none;\" title=\"All active users of TACC resources are eligible to run jobs through the TACC-2-BOINC infrastructure and qualify as researchers.\"><font size=+3>".tra("Log in as a Researcher")."</a></font>";

    // Redirects to index.php courtesy of Carlos Redondo, Gerald Joshua, Thomas Johnson III 


    form_start("./login_as_a_researcher_form_action.php","post");
    form_input_text(
        sprintf('<span title="%s">%s</span>',
            tra("Identifies you on our web site. Use your real name or a nickname."),
            tra("Username")       ), 
        "username","","","name='username' placeholder='username' id='username'"
    );
    form_input_text(
        sprintf('<span title="%s">%s</span>',
            tra("Must be a valid address of the form 'name@domain'."),
            tra("Password")
        ),
        "password","","","name='password' placeholder='password' id='password'",passwd_visible_checkbox("password")
    );


    //form_start("./login_as_a_researcher_form_action.php","post");
    /*login_as_a_researcher_form();*/
    /*Commentedout by Joshua
    form_submit("Log in");
    End of the edit*/

    //Added by Gerald Joshua
    echo '<input class="btn btn-success" type="submit" id="submitBtn" value="Log In" style="font-weight: bold; margin-left: 35%;">';
    //End of Joshua's edit
    form_end();


    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/



    echo "<br><br>";
    /*
    echo "
      <div style=\"margin-left: 36%;margin-top: 10px;\"><a href=\"https://portal.tacc.utexas.edu/home?p_p_id=58&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&saveLastPath=0&_58_struts_action=%2Flogin%2Flogin\" class=\"btn btn-success\">Login as a Researcher</a>
      </div>";
    */

    /*
    echo '<br></br';
    echo "<a data-toggle=\"tooltip\"  style=\"margin-left: 36%;font-size: 24px;border-bottom:1px dotted #000;text-decoration: none;\" title=\"All active users of TACC resources are eligible to run jobs through the TACC-2-BOINC infrastructure and qualify as researchers.\">Log In as a Researcher</a>
    	<div style=\"margin-left: 36%;margin-top: 10px;\"><a href=\"https://portal.tacc.utexas.edu/home?p_p_id=58&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&saveLastPath=0&_58_struts_action=%2Flogin%2Flogin\" class=\"btn btn-success\">Log In</a></div>";
    */
    //End of Gerald Joshua's edit (From Joshua's edit to Log In page)

    /*
    echo "
        <script type=\"text/javascript\">
            document.f.email_addr.focus();
        </script>
    ";
    */
    echo 
    "<!-- Jquery library was added by Gerald Joshua -->
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script>
    document.getElementById(\"password\").type=\"password\";
    //Added by Gerald Joshua
    $('#submitBtn').prop('disabled', true);
    $('#username').bind('input propertychange', function() {
      			if(this.value.length > 0 && $('#password').val().length > 0){
    				$('#submitBtn').prop('disabled', false);
    			}
    			else{
    				$('#submitBtn').prop('disabled', true);
    			}
    		});
    $('#password').bind('input propertychange', function() {
      			if(this.value.length > 0 && $('#username').val().length > 0){
    				$('#submitBtn').prop('disabled', false);
    			}
    			else{
    				$('#submitBtn').prop('disabled', true);
    			}
    		});

    //End of the edit by Joshua
    </script>
    ";
  }
}
page_tail();
?>
